/**
 * 첨부/미디어 URL·파일명 접근 통일 — 직접 msg.url 만 가정하지 않음
 * message.attachment (표준) + meta.* + top-level url 병합
 */
import type { ChatAttachmentStandardV2, ChatMessageV2 } from './messageSchema';

function metaOf(msg: ChatMessageV2 | null | undefined): Record<string, unknown> {
  const m = msg?.meta;
  return m && typeof m === 'object' ? (m as Record<string, unknown>) : {};
}

function attOf(msg: ChatMessageV2 | null | undefined): Partial<ChatAttachmentStandardV2> | undefined {
  const a = msg?.attachment;
  return a && typeof a === 'object' ? a : undefined;
}

/** 요구사항 순서: attachment.remoteUrl → … → legacy top-level msg.url → localUri */
export function resolveAttachmentRemoteUrl(msg: ChatMessageV2 | null | undefined): string | null {
  if (!msg) return null;
  try {
    const a = attOf(msg) as Record<string, unknown> | undefined;
    const m = metaOf(msg);
    const chain: unknown[] = [
      a?.remoteUrl,
      a?.url,
      a?.fileUrl,
      a?.downloadURL,
      (msg as any)?.url,
      m.remoteUrl,
      m.url,
      m.fileUrl,
      m.downloadURL,
      m.mediaUrl,
      a?.localUri,
      m.localUri,
    ];
    for (const x of chain) {
      if (typeof x === 'string' && x.trim().length > 0) return x.trim();
    }
  } catch {
    /* optional chaining 전제로도 스냅샷 이상치 방지 */
  }
  return null;
}

/** 썸네일: thumbnailUrl → thumbUrl → previewUrl → resolved 원격 → localUri */
export function resolveAttachmentThumbUrl(msg: ChatMessageV2 | null | undefined): string | null {
  if (!msg) return null;
  try {
    const a = attOf(msg) as Record<string, unknown> | undefined;
    const m = metaOf(msg);
    const remote = resolveAttachmentRemoteUrl(msg);
    const chain: unknown[] = [
      typeof msg.thumbnailUrl === 'string' ? msg.thumbnailUrl : null,
      a?.thumbnailUrl,
      a?.thumbUrl,
      a?.previewUrl,
      m.thumbnailUrl,
      m.thumbUrl,
      m.previewUrl,
      remote,
      typeof a?.localUri === 'string' ? a.localUri : null,
      typeof m.localUri === 'string' ? m.localUri : null,
    ];
    for (const x of chain) {
      if (typeof x === 'string' && x.trim().length > 0) return x.trim();
    }
  } catch {
    /* noop */
  }
  return null;
}

/**
 * Firestore에 남은 메시지 기준으로, 상대 기기에서도 열 수 있는 원격 URL(https)만.
 * (병합 시 `final` 판정 — file:// 는 발신자 기기 전용이라 제외)
 */
export function getHttpsAttachmentUrl(msg: ChatMessageV2 | null | undefined): string {
  if (!msg) return '';
  try {
    const a = attOf(msg) as Record<string, unknown> | undefined;
    const m = metaOf(msg);
    const chain: unknown[] = [
      a?.remoteUrl,
      a?.url,
      a?.fileUrl,
      a?.downloadURL,
      (msg as any)?.url,
      m.remoteUrl,
      m.url,
      m.fileUrl,
      m.downloadURL,
      m.mediaUrl,
      a?.thumbnailUrl,
      m.thumbnailUrl,
    ];
    for (const x of chain) {
      if (typeof x === 'string' && x.trim().length > 0 && /^https?:\/\//i.test(x.trim())) return x.trim();
    }
  } catch {
    /* noop */
  }
  return '';
}

/** 원격 재생/다운로드용 HTTPS URL (없으면 undefined) */
export function getMediaRemoteUrl(msg: ChatMessageV2 | null | undefined): string | undefined {
  const r = resolveAttachmentRemoteUrl(msg);
  return r || undefined;
}

/** 로컬 미리보기(전송 중·실패 재시도) */
export function getLocalPreviewUri(msg: ChatMessageV2 | null | undefined): string | undefined {
  const m = metaOf(msg);
  const a = attOf(msg);
  const u = typeof a?.localUri === 'string' ? a.localUri.trim() : '';
  if (u) return u;
  const u2 = typeof m.localUri === 'string' ? String(m.localUri).trim() : '';
  return u2 || undefined;
}

/** 썸네일/이미지 표시용 */
export function getThumbSourceUri(msg: ChatMessageV2 | null | undefined): string | undefined {
  const t = resolveAttachmentThumbUrl(msg);
  return t || undefined;
}

/** Storage 경로용 `타임스탬프_messageId.ext` 등 — 사용자가 고른 원본명이 아님 */
export function looksLikeAutoGeneratedMediaFilename(name: string, messageId?: string): boolean {
  const n = String(name || '').trim();
  if (!n) return false;
  if (messageId && n.includes(String(messageId))) return true;
  if (/^\d{10,}_[a-f0-9-]{8,}\.[a-z0-9]+$/i.test(n)) return true;
  if (/^\d{13,}_[^/\\]+\.[a-z0-9]+$/i.test(n)) return true;
  return false;
}

/** 말풍선·미리보기 제목: 원본 파일명 우선 */
export function getDisplayFileName(msg: ChatMessageV2 | null | undefined): string {
  if (!msg) return '';
  const a = attOf(msg);
  const m = metaOf(msg);
  const mid = String(msg.id || '');
  const orig =
    (typeof a?.originalName === 'string' && a.originalName.trim()) ||
    (typeof m.originalName === 'string' && String(m.originalName).trim()) ||
    '';
  const fn = typeof msg.filename === 'string' ? msg.filename.trim() : '';
  if (orig) return orig;
  if (fn && !looksLikeAutoGeneratedMediaFilename(fn, mid)) return fn;
  if (fn) return fn;
  return '';
}

/** 미리보기/외부 열기용: 원격 없으면 로컬 */
export function getMediaPlayableUri(msg: ChatMessageV2 | null | undefined): string {
  return getMediaRemoteUrl(msg) || getLocalPreviewUri(msg) || '';
}

/** 안전한 링크 URL (link.url 직접 접근 금지 대체) */
export function getLinkUrlSafe(msg: ChatMessageV2 | null | undefined): string {
  try {
    const u = msg?.link && typeof (msg.link as any).url === 'string' ? String((msg.link as any).url).trim() : '';
    return u;
  } catch {
    return '';
  }
}

/** __DEV__ 전용: 첨부 구조 스냅샷 (메모리 절약 — 프로덕션 무출력) */
export function debugLogAttachmentSnapshot(label: string, msg: ChatMessageV2 | null | undefined): void {
  try {
    // eslint-disable-next-line no-undef
    if (typeof __DEV__ === 'undefined' || !__DEV__) return;
    const att = msg?.attachment as Record<string, unknown> | undefined;
    const payload = {
      label,
      id: msg?.id,
      type: msg?.type,
      status: msg?.status,
      hasAttachment: !!msg?.attachment,
      topUrl: typeof (msg as any)?.url === 'string' ? String((msg as any).url).slice(0, 120) : null,
      attKeys: att ? Object.keys(att) : [],
      resolvedRemote: resolveAttachmentRemoteUrl(msg),
      resolvedThumb: resolveAttachmentThumbUrl(msg),
      displayName: getDisplayFileName(msg),
    };
    // eslint-disable-next-line no-console
    console.log('[YY_CHAT_V2_ATTACH]', JSON.stringify(payload));
  } catch {}
}

/** 답장/전달/공유용: 텍스트 없을 때 원격 URL·링크 문자열 */
export function resolveMessageShareText(msg: ChatMessageV2 | null | undefined): string {
  if (!msg) return '';
  const t = String(msg.text || '').trim();
  if (t) return t;
  const remote = resolveAttachmentRemoteUrl(msg);
  if (remote) return remote;
  try {
    const linkU = getLinkUrlSafe(msg);
    if (linkU) return linkU;
  } catch {
    /* noop */
  }
  return '';
}

function looksLikeHttpUrl(s: string): boolean {
  return /^https?:\/\//i.test(String(s || '').trim());
}

/** 답장 메타에 넣을 미리보기 문구 — 미디어는 URL 대신 파일명·유형 (말풍선 2줄용) */
export function resolveReplyPreviewText(msg: ChatMessageV2 | null | undefined): string {
  if (!msg) return '';
  const t = String(msg.text || '').trim();
  if (t) return t.slice(0, 120);
  const name = getDisplayFileName(msg);
  if (name) return name.slice(0, 120);
  const type = String(msg.type || '');
  if (type === 'image') return '사진';
  if (type === 'video') return '동영상';
  if (type === 'file') return '파일';
  if (type === 'audio') return '음성';
  if (type === 'location') return '위치';
  if (type === 'url') return '링크';
  if (type === 'poll') return '투표';
  if (type === 'qr') return 'QR';
  return `[${type || 'message'}]`;
}

/** 이미 저장된 답장(meta.replyTo) 표시용 — 예전에 URL만 넣었던 메시지도 읽기 가능 */
export function formatReplySnapshotSubtitle(replyTo: {
  type?: string;
  text?: string;
} | null | undefined): string {
  if (!replyTo) return '';
  const text = String(replyTo.text || '').trim();
  const type = String(replyTo.type || '');
  if (text && !looksLikeHttpUrl(text)) {
    return text.length > 120 ? `${text.slice(0, 117)}…` : text;
  }
  if (text && looksLikeHttpUrl(text)) {
    try {
      const u = new URL(text);
      const seg = u.pathname.split('/').filter(Boolean).pop();
      if (seg) {
        const decoded = decodeURIComponent(seg);
        return decoded.length > 100 ? `${decoded.slice(0, 97)}…` : decoded;
      }
    } catch {
      /* noop */
    }
  }
  if (type === 'image') return '사진';
  if (type === 'video') return '동영상';
  if (type === 'file') return '파일';
  if (type === 'audio') return '음성';
  if (type === 'location') return '위치';
  if (type === 'url') return '링크';
  if (type === 'poll') return '투표';
  if (type === 'qr') return 'QR';
  if (text) return text.slice(0, 120);
  return `[${type || 'message'}]`;
}

/** 썸네일로 쓰기엔 동영상 스트림 URL이라 Image가 못 그리는 경우 */
export function isLikelyVideoStreamUri(uri: string | null | undefined): boolean {
  const u = String(uri || '').trim().toLowerCase();
  if (!u) return false;
  return /\.(mp4|m4v|webm|mov|mkv|avi)(\?|#|$)/i.test(u);
}
