import type { ChatMessageV2 } from '../core/messageSchema';
import { isMediaMessageV2 } from '../core/messageSchema';
import { getHttpsAttachmentUrl, looksLikeAutoGeneratedMediaFilename } from '../core/attachmentAccess';

/**
 * Firestore 스냅샷이 optimistic 메시지를 덮을 때 meta.localUri 가 빠지면
 * 전송 중 썸네일·재시도가 깨집니다. 서버가 url + 최종 status 를 줄 때만 incoming 을 그대로 씁니다.
 */
export function mergeIncomingChatMessageV2(prev: ChatMessageV2 | undefined, incoming: ChatMessageV2): ChatMessageV2 {
  if (!prev || prev.id !== incoming.id) return incoming;

  let merged: ChatMessageV2 = incoming;

  if (isMediaMessageV2(prev) && isMediaMessageV2(incoming) && prev.type === incoming.type) {
    const incHttps = getHttpsAttachmentUrl(incoming);
    const final =
      incHttps.length > 0 &&
      (incoming.status === 'sent' || incoming.status === 'ready' || incoming.status === 'uploaded');
    if (!final) {
      const prevLocal =
        String((prev.attachment as any)?.localUri || prev.meta?.localUri || '').trim();
      const incLocal =
        String((incoming.attachment as any)?.localUri || incoming.meta?.localUri || '').trim();
      if (prevLocal && !incLocal) {
        merged = {
          ...incoming,
          meta: { ...(incoming.meta || {}), localUri: prevLocal },
          attachment: incoming.attachment
            ? { ...incoming.attachment, localUri: prevLocal }
            : prev.attachment
              ? { ...prev.attachment, localUri: prevLocal }
              : incoming.attachment,
        };
      }
    } else {
      merged = incoming;
    }
    const prevFn = String(prev.filename || '').trim();
    const incFn = String(merged.filename || '').trim();
    if (prevFn && (!incFn || looksLikeAutoGeneratedMediaFilename(incFn, merged.id))) {
      merged = { ...merged, filename: prev.filename };
    }
    const prevOrig = String((prev.attachment as any)?.originalName || (prev.meta as any)?.originalName || '').trim();
    const incOrig = String((merged.attachment as any)?.originalName || (merged.meta as any)?.originalName || '').trim();
    if (prevOrig && (!incOrig || looksLikeAutoGeneratedMediaFilename(incOrig, merged.id))) {
      merged = {
        ...merged,
        meta: { ...(merged.meta || {}), originalName: prevOrig },
        attachment: merged.attachment ? { ...merged.attachment, originalName: prevOrig } : prev.attachment,
      };
    }
    const prevAtt = prev.attachment;
    const incAtt = merged.attachment;
    if (prevAtt && incAtt) {
      const pOrig = String(prevAtt.originalName || '').trim();
      const iOrig = String(incAtt.originalName || '').trim();
      const pickOrig =
        pOrig && (!iOrig || looksLikeAutoGeneratedMediaFilename(iOrig, merged.id)) ? pOrig : iOrig || pOrig || incAtt.originalName;
      const finalOrig = String(pickOrig || iOrig || pOrig || incAtt.originalName || 'attachment').trim();
      merged = {
        ...merged,
        attachment: {
          ...incAtt,
          originalName: finalOrig,
          localUri: String(incAtt.localUri || prevAtt.localUri || '').trim() || incAtt.localUri,
          remoteUrl: String(incAtt.remoteUrl || prevAtt.remoteUrl || '').trim() || incAtt.remoteUrl,
          thumbnailUrl: String(incAtt.thumbnailUrl || prevAtt.thumbnailUrl || '').trim() || incAtt.thumbnailUrl,
          storageName: String(incAtt.storageName || prevAtt.storageName || '').trim() || incAtt.storageName,
        },
      };
    } else if (prevAtt && !incAtt) {
      merged = { ...merged, attachment: prevAtt };
    }
  }

  const prevCreated = Number(prev.createdAt || 0);
  const incCreated = Number(merged.createdAt || 0);
  if (prevCreated > 0 && (!incCreated || incCreated <= 0)) {
    merged = { ...merged, createdAt: prevCreated };
  }

  // 로컬에서 roomSummaryApplied 반영 직후 스냅샷이 옛 필드만 줄 때 재시도 시 미읽음 중복 방지 플래그 유지
  const prevSummarized = !!(prev as any)?.meta?.roomSummaryApplied;
  const incSummarized = !!(merged as any)?.meta?.roomSummaryApplied;
  if (prevSummarized && !incSummarized) {
    merged = { ...merged, meta: { ...(merged.meta || {}), roomSummaryApplied: true } };
  }

  return merged;
}
