$ErrorActionPreference = 'Stop'

$prod = @"
EXPO_PUBLIC_ENV=prod
EXPO_PUBLIC_AUTH_PROVIDER=firebase
EXPO_PUBLIC_ENABLE_MOCK_AUTH=false
EXPO_PUBLIC_FIREBASE_API_KEY=AIzaSyB-qGVg2R0N1VfrY68cucdnz3_00y2RphI
EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=yooyland-prod.firebaseapp.com
EXPO_PUBLIC_FIREBASE_PROJECT_ID=yooyland-prod
EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=yooyland-prod.appspot.com
EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=712419325837
EXPO_PUBLIC_FIREBASE_APP_ID=1:712419325837:web:5cb8eeebba6a8838922fc4
EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=G-XZVSZSJ6EV
"@

$dev = @"
EXPO_PUBLIC_ENV=dev
EXPO_PUBLIC_AUTH_PROVIDER=firebase
EXPO_PUBLIC_ENABLE_MOCK_AUTH=false
EXPO_PUBLIC_FIREBASE_API_KEY=AIzaSyCjsqHT9VUwjfHbkOgE1APt_CeOcTCCHJk
EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=yooyland-dev.firebaseapp.com
EXPO_PUBLIC_FIREBASE_PROJECT_ID=yooyland-dev
EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=yooyland-dev.appspot.com
EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=100235868327
EXPO_PUBLIC_FIREBASE_APP_ID=1:100235868327:web:faf04af748faf8957d8382
EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=G-LQWFJKSESR
"@

$stg = @"
EXPO_PUBLIC_ENV=stg
EXPO_PUBLIC_AUTH_PROVIDER=firebase
EXPO_PUBLIC_ENABLE_MOCK_AUTH=false
EXPO_PUBLIC_FIREBASE_API_KEY=AIzaSyDRLsj5b_IYXaPZ44650EzMAqCXiz8vj-U
EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=yooyland-stg.firebaseapp.com
EXPO_PUBLIC_FIREBASE_PROJECT_ID=yooyland-stg
EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=yooyland-stg.appspot.com
EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=228684575961
EXPO_PUBLIC_FIREBASE_APP_ID=1:228684575961:web:76c2f00f0b9ed670fefac8
EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=G-V2XJ31EKLX
"@

Set-Content -Path ".env.prod" -Value $prod -Encoding UTF8
Set-Content -Path ".env.dev" -Value $dev -Encoding UTF8
Set-Content -Path ".env.stg" -Value $stg -Encoding UTF8

Write-Host "Created .env.prod, .env.dev, .env.stg"

